---

- block:

  - name: set pin facts
    set_fact:
      _pin_package: auditbeat
      _pin_version: "{{ elasticsearch_release }}"

  - name: set elasticsearch preferences file
    template:
      src: pin.pref.j2
      dest: "/etc/apt/preferences.d/auditbeat.pref"
      owner: root
      group: root
      mode: 0644

  - name: install auditbeat
    apt:
      name: "{{ packages }}"
      state: latest
      dpkg_options: 'force-confnew,force-confdef'
      autoclean: yes
      autoremove: yes
      update_cache: yes
      cache_valid_time: 3600
    vars:
      packages:
      - auditbeat
    register: _auditbeat_installed

  - name: uncomment original elasticsearch host
    lineinfile:
      path: /etc/auditbeat/auditbeat.yml
      regexp: "^  hosts: [\"localhost:9200\"]"
      line: "  #hosts: [\"localhost:9200\"]"
    when: elasticsearch_listen_ip is defined

  - name: set elasticsearch ip
    lineinfile:
      path: /etc/auditbeat/auditbeat.yml
      regexp: '^  hosts:'
      line: "  hosts: [\"{{ elasticsearch_listen_ip }}:9200\"]"
      insertafter: '  #hosts: [\"localhost:9200\"]'
    when: elasticsearch_listen_ip is defined

  - name: restart auditbeat
    service:
      name: auditbeat
      enabled: yes
      state: restarted

  when: elasticsearch_install_auditbeat

- block:

  - name: set pin facts
    set_fact:
      _pin_package: filebeat
      _pin_version: "{{ elasticsearch_release }}"

  - name: set elasticsearch preferences file
    template:
      src: pin.pref.j2
      dest: "/etc/apt/preferences.d/filebeat.pref"
      owner: root
      group: root
      mode: 0644

  - name: install filebeat
    apt:
      name: "{{ packages }}"
      state: latest
      dpkg_options: 'force-confnew,force-confdef'
      autoclean: yes
      autoremove: yes
      update_cache: yes
      cache_valid_time: 3600
    vars:
      packages:
      - filebeat
    register: _filebeat_installed

  - name: uncomment original elasticsearch host
    lineinfile:
      path: /etc/filebeat/filebeat.yml
      regexp: "^  hosts: [\"localhost:9200\"]"
      line: "  #hosts: [\"localhost:9200\"]"
    when: elasticsearch_listen_ip is defined

  - name: set elasticsearch ip
    lineinfile:
      path: /etc/filebeat/filebeat.yml
      regexp: '^  hosts:'
      line: "  hosts: [\"{{ elasticsearch_listen_ip }}:9200\"]"
      insertafter: '  #hosts: [\"localhost:9200\"]'
    when: elasticsearch_listen_ip is defined

  - name: restart filebeat
    service:
      name: filebeat
      enabled: yes
      state: restarted

  when: elasticsearch_install_filebeat

- block:

  - name: set pin facts
    set_fact:
      _pin_package: heartbeat-elastic
      _pin_version: "{{ elasticsearch_release }}"

  - name: set elasticsearch preferences file
    template:
      src: pin.pref.j2
      dest: "/etc/apt/preferences.d/heartbeat-elastic.pref"
      owner: root
      group: root
      mode: 0644

  - name: install heartbeat
    apt:
      name: "{{ packages }}"
      state: latest
      dpkg_options: 'force-confnew,force-confdef'
      autoclean: yes
      autoremove: yes
      update_cache: yes
      cache_valid_time: 3600
    vars:
      packages:
      - heartbeat-elastic
    register: _heartbeat_installed

  - name: uncomment original elasticsearch host
    lineinfile:
      path: /etc/heartbeat/heartbeat.yml
      regexp: "^  hosts: [\"localhost:9200\"]"
      line: "  #hosts: [\"localhost:9200\"]"
    when: elasticsearch_listen_ip is defined

  - name: set elasticsearch ip
    lineinfile:
      path: /etc/heartbeat/heartbeat.yml
      regexp: '^  hosts:'
      line: "  hosts: [\"{{ elasticsearch_listen_ip }}:9200\"]"
      insertafter: '  #hosts: [\"localhost:9200\"]'
    when: elasticsearch_listen_ip is defined

  - name: restart heartbeat
    service:
      name: heartbeat-elastic
      enabled: yes
      state: restarted

  when: elasticsearch_install_heartbeat

- block:

  - name: set pin facts
    set_fact:
      _pin_package: metricbeat
      _pin_version: "{{ elasticsearch_release }}"

  - name: set elasticsearch preferences file
    template:
      src: pin.pref.j2
      dest: "/etc/apt/preferences.d/metricbeat.pref"
      owner: root
      group: root
      mode: 0644

  - name: install metricbeat
    apt:
      name: "{{ packages }}"
      state: latest
      dpkg_options: 'force-confnew,force-confdef'
      autoclean: yes
      autoremove: yes
      update_cache: yes
      cache_valid_time: 3600
    vars:
      packages:
      - metricbeat
    register: _metricbeat_installed

  - name: uncomment original elasticsearch host
    lineinfile:
      path: /etc/metricbeat/metricbeat.yml
      regexp: "^  hosts: [\"localhost:9200\"]"
      line: "  #hosts: [\"localhost:9200\"]"
    when: elasticsearch_listen_ip is defined

  - name: set elasticsearch ip
    lineinfile:
      path: /etc/metricbeat/metricbeat.yml
      regexp: '^  hosts:'
      line: "  hosts: [\"{{ elasticsearch_listen_ip }}:9200\"]"
      insertafter: '  #hosts: [\"localhost:9200\"]'
    when: elasticsearch_listen_ip is defined

  - name: restart metricbeat
    service:
      name: metricbeat
      enabled: yes
      state: restarted

  when: elasticsearch_install_metricbeat

- block:

  - name: set pin facts
    set_fact:
      _pin_package: packetbeat
      _pin_version: "{{ elasticsearch_release }}"

  - name: set elasticsearch preferences file
    template:
      src: pin.pref.j2
      dest: "/etc/apt/preferences.d/packetbeat.pref"
      owner: root
      group: root
      mode: 0644

  - name: install packetbeat
    apt:
      name: "{{ packages }}"
      state: latest
      dpkg_options: 'force-confnew,force-confdef'
      autoclean: yes
      autoremove: yes
      update_cache: yes
      cache_valid_time: 3600
    vars:
      packages:
      - packetbeat
    register: _packetbeat_installed

  - name: uncomment original elasticsearch host
    lineinfile:
      path: /etc/packetbeat/packetbeat.yml
      regexp: "^  hosts: [\"localhost:9200\"]"
      line: "  #hosts: [\"localhost:9200\"]"
    when: elasticsearch_listen_ip is defined

  - name: set elasticsearch ip
    lineinfile:
      path: /etc/packetbeat/packetbeat.yml
      regexp: '^  hosts:'
      line: "  hosts: [\"{{ elasticsearch_listen_ip }}:9200\"]"
      insertafter: '  #hosts: [\"localhost:9200\"]'
    when: elasticsearch_listen_ip is defined

  - name: restart packetbeat
    service:
      name: packetbeat
      enabled: yes
      state: restarted

  when: elasticsearch_install_packetbeat

...
