---

- name: install packages
  apt:
    name: "{{item}}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoremove: yes
    update_cache: yes
  with_items:
  - apt-transport-https
  - software-properties-common
  - python-pexpect

#- name: install required python modules
#  pip:
#    name: "{{ item }}"
#    extra_args: --upgrade
#  with_items:
#  - pexpect

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add elastic repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    state: present
    filename: elastic-6.x

- name: install beats
  include: beats.yml

...
